version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    volumes:
      - /home/yeondcho/data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
    networks:
      - wordpress_network

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /home/yeondcho/data/nginx:/var/www/html
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    restart: always
    networks:
      - wordpress_network

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/yeondcho/data/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    networks:
      - wordpress_network

networks:
  wordpress_network:
    driver: bridge
